name: TVSliderDemo
options:
  bundleIdPrefix: com.creaturesurvive
packages:
  TVSlider:
    path: ..
targets:
  TVSliderDemo:
    type: application
    platform: tvOS
    deploymentTarget: "17.0"
    sources: [TVSliderDemo]
    dependencies:
      - package: TVSlider
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.creaturesurvive.TVSliderDemo
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: RUMWXF5QY3
  TVSliderDemoUITests:
    type: bundle.ui-testing
    platform: tvOS
    deploymentTarget: "17.0"
    sources: [TVSliderDemoUITests]
    dependencies:
      - target: TVSliderDemo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.creaturesurvive.TVSliderDemoUITests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "6.0"
        TEST_TARGET_NAME: TVSliderDemo
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: RUMWXF5QY3
schemes:
  TVSliderDemo:
    build:
      targets:
        TVSliderDemo: all
        TVSliderDemoUITests: [test]
    test:
      targets: [TVSliderDemoUITests]
